name: fitness_workout
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.4
  video_player: ^2.9.5
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  fl_chart: ^0.70.2
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.6.2
  readmore: ^2.1.0
  calendar_agenda:
    path: dev_lib/calendar_agenda/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/bicepCurl.py
    - assets/videos/
    - assets/videos/bicep_s.mov